country: AT
must_cover:
- website_id: at:adeg.at
- website_id: at:apotheke.at
- website_id: at:billa.at
- website_id: at:bipa.at
- website_id: at:denns-biomarkt.at
- website_id: at:douglas.at
- website_id: at:interspar.at
- website_id: at:ecco-verde.at
- website_id: at:hofer.at
- website_id: at:lidl.at
- website_id: at:mpreis.at
- website_id: at:marionnaud.at
- website_id: at:mueller.at
- website_id: at:nahundfrisch.at
- website_id: at:naturitas.at
- website_id: at:notino.at
- website_id: at:penny.at
- website_id: at:reformstark.at
- website_id: at:spar.at
- website_id: at:shop-apotheke.at
- website_id: at:sutterluety.at
- website_id: at:unimarkt.at
- website_id: at:dm.at
long_tail: []
gates:
  min_retailers_active: 2
  max_zero_result_retailers: 0
  ean_or_sku_presence_rate: 0.6
  unit_price_sanity:
    eur_per_l:
    - 1
    - 200
  wow_drop_threshold_pct: 70
