positive:
  - olijfolie
  - huile d'olive
  - olive oil
  - extra vierge
  - extra virgin
  - extravierge
  - azeite
  - olivenöl
brands_hint:
  - bertolli
  - carbone
  - carapelli
  - de cecco
  - colavita
  - monini
  - casa rinaldi
  - coricelli
